trigger: none

pool:
  name: OnPrem

variables:
- group: SonarQube
- group: Python

jobs:
  - job: Tests
        
    steps:
    - task: UsePythonVersion@0
      inputs:
          versionSpec: $(PYTHON_VERSION)

    - script: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install -r requirement-dev.txt
      displayName: Install Dependencies
      workingDirectory: $(System.DefaultWorkingDirectory)/webhook_listener
    
    - script: |
        pytest test_function_app.py
      displayName: Unit Tests
      workingDirectory: $(System.DefaultWorkingDirectory)/webhook_listener

    - script: |
        ruff format --check --diff *.py
      displayName: Check formatting
      workingDirectory: $(System.DefaultWorkingDirectory)/webhook_listener

    - script: |
        ruff check *.py
      displayName: Check lint
      workingDirectory: $(System.DefaultWorkingDirectory)/webhook_listener

    - task: SonarQubePrepare@7
      inputs:
        SonarQube: $(SONARQUBE_SERVICE_CONNECTION_NAME)
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: $(SONARQUBE_PROJECT_KEY)
        cliProjectName: $(SONARQUBE_PROJECT_NAME)
        cliSources: $(System.DefaultWorkingDirectory)/webhook_listener

    - task: SonarQubeAnalyze@7
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarQubePublish@7
      inputs:
        pollingTimeoutSec: '300'