trigger:
  branches:
     include:
       - main
  paths:
    include:
      - IaC/**
      - webhook_listener/**

pool:
  name: OnPrem

stages:
  - stage: DetermineChangedDirs
    jobs:
      - job: CheckChanges
        steps:
          - script: |
              echo "##[group]Checking which folders changed..."
              git fetch origin main
              git diff --name-only origin/main...HEAD > changed.txt
              echo "##[endgroup]"

              echo "##[group]Set Variables..."
              if grep -q "IaC/" changed.txt; then echo "##vso[task.setvariable variable=runIACCI]true";fi
              if grep -q "webhook_listener/" changed.txt; then echo "##vso[task.setvariable variable=runWebhookListenerCI]true";fi
              echo "##[endgroup]"

  - stage: RunCIPipelines
    dependsOn: DetermineChangedDirs
    variables:
    - group: Orchestrator
    jobs:
      - job: IaCCI
        condition: eq(variables['runIACCI'], 'true')
        steps:
          - script: |
              curl -X POST \
                -H "Authorization: Bearer $(System.AccessToken)" \
                -H "Content-Type: application/json" \
                "https://dev.azure.com/$(System.Organization)/$(System.TeamProject)/_apis/pipelines/$(PIPELINE_ID_IAC)/runs?api-version=7.1"
            displayName: Trigger IaC CI


      - job: WebhookListenerCI
        condition: eq(variables['runWebhookListenerCI'], 'true')
        steps:
          - script: |
              curl -X POST \
              -H "Authorization: Bearer $(System.AccessToken)" \
              -H "Content-Type: application/json" \
              "https://dev.azure.com/$(System.Organization)/$(System.TeamProject)/_apis/pipelines/$(PIPELINE_ID_WEBHOOK_LISTENER)/runs?api-version=7.1"
            displayName: Trigger WebhookListener CI